import { expect, test } from "@playwright/test";
import { openStudio, showStructure } from "./support/studio.js";

/**
 * A label an author types, and the shell that prints it with `innerHTML`.
 *
 * Studio's chrome is rewritten as markup — `Region.update` assigns `innerHTML`, and the outline
 * builds a node's row as a template string. An author's label goes into that string, and a project
 * is a file: shared, imported, generated by something else. So the label is the shortest path from
 * data somebody else wrote to markup this app evaluates.
 *
 * `escapeHtml` is applied where the label is read — `escapeHtml(n.label || n.name)` — and this asks
 * the page rather than the source, because the question is not whether one call site escapes but
 * whether the value survives every hop between the input and the screen as text.
 *
 * Four payloads, each closing a different thing the surrounding markup opens: an attribute, a
 * `<summary>`, nothing at all, and an attribute that needs no closing tag to run. Each is checked
 * three ways — nothing executed, nothing was injected, and the label reads back **exactly** what was
 * typed, which is the half that says the escaping did not quietly mangle it either.
 *
 * The last check is why this is not only a security spec: a label that arrives as `&lt;script&gt;`
 * in the outline is safe and wrong, and a person renaming a field would be looking at something they
 * did not type.
 */

/** Each one closes a different construct the outline's markup puts a label inside. */
const PAYLOADS = [
  '"><img src=x onerror="window.__pwned=1">',
  "</summary><img src=y onerror='window.__pwned=2'>",
  "<script>window.__pwned=3</script>",
  '" autofocus onfocus="window.__pwned=4"',
];

test("a label that tries to be markup stays a label", async ({ page }) => {
  const pageErrors: string[] = [];
  page.on("pageerror", (error) => pageErrors.push(error.message));

  await openStudio(page);
  await showStructure(page);
  await page.locator('[data-template="text"]').click();

  // The control: an ordinary label reaches the outline, so a payload that does not appear later is
  // a payload that was escaped rather than one the outline never shows.
  await page.locator("[data-label]").fill("Ordinary");
  await page.locator("[data-label]").blur();
  await expect(page.locator(".outline .node-label")).toHaveText(/Ordinary/);

  for (const payload of PAYLOADS) {
    await page.locator("[data-label]").fill(payload);
    await page.locator("[data-label]").blur();
    await expect(page.locator(".outline .node-label")).toHaveText(payload, { timeout: 4000 });

    const seen = await page.evaluate(() => ({
      executed: (window as never as { __pwned?: number }).__pwned ?? null,
      injected: document.querySelectorAll('img[src="x"], img[src="y"], script:not([src])').length,
      autofocused: document.querySelectorAll("[onfocus]").length,
    }));

    expect(seen.executed, `the payload ran: ${payload}`).toBeNull();
    expect(seen.injected, `the payload became an element: ${payload}`).toBe(0);
    expect(seen.autofocused, `the payload became an attribute: ${payload}`).toBe(0);
  }

  expect(pageErrors, `the page reported: ${pageErrors.join(" | ")}`).toEqual([]);
});
