/**
 * A key nobody declared, offered to the three surfaces that should refuse it.
 *
 * A document is checked in three places before it becomes a form, and they are meant to agree about
 * what a document may contain:
 *
 * - **the TypeScript type**, when a document is written as a literal — an excess property is a
 *   compile error;
 * - **the published JSON Schema**, `spec/dynamic-form-v3.schema.json`, which closes its objects
 *   seventeen times with `"additionalProperties": false` — and which `apps/vscode/package.json`
 *   points every `*.form.json` at, so an editor says so while the document is being written;
 * - **the parser**, which is the only one of the three that decides what actually reaches a form.
 *
 * The third refuses nothing. Measured across every slot a document has:
 *
 *   an unknown key on a field          nothing
 *   an unknown key on a rule           nothing
 *   an unknown key on a validation     nothing
 *   an unknown key on a layout node    nothing
 *   an unknown key on an option        nothing
 *
 * Which matters because the two surfaces that *do* refuse are the two a document can arrive without.
 * A form config stored in a CMS, generated by a model, or assembled by a server was never a
 * TypeScript literal and never passed an editor; the parser is all it meets. And the parser is where
 * `ai-generated-forms.md` puts the enforcement in as many words: *"the parser stays the enforcement
 * layer — prompts reduce waste, `parseDynamicFields()` enforces the supported contract."*
 *
 * This is not an argument for refusing every unknown key. A document may carry members a reader
 * predating them does not know, and that is what lets a v3 document be read by a v2 parser. The
 * assertion is narrower and takes its boundary from the repository rather than from an opinion:
 * **what the published JSON Schema refuses, the parser reports too.** The schema already draws the
 * line; the parser is silent about the same line.
 *
 * `field()` and `createForm` already do this for their own options — `createForm was given
 * "autoActivte", which it does not read` — so the sentence exists in this codebase, twice.
 */

import { parseDynamicForm } from "@modyra/core";

import { battle } from "../../harness/battle.mjs";
import { expectClaim, expectEqual } from "../../harness/assertions.mjs";

/** Two fields, so a slot that names one has something to name. */
const FIELDS = Object.freeze([
  Object.freeze({ name: "a", kind: "text", label: "A" }),
  Object.freeze({ name: "b", kind: "text", label: "B" }),
]);

/** One document per slot, each carrying a key the contract does not declare. */
const SLOTS = Object.freeze([
  {
    slot: "a field",
    document: { version: 2, fields: [{ ...FIELDS[0], nonsenseKey: 1 }, FIELDS[1]] },
  },
  {
    slot: "an option",
    document: {
      version: 2,
      fields: [
        { name: "a", kind: "select", label: "A", options: [{ value: "x", label: "X", nonsenseKey: 1 }] },
      ],
    },
  },
  {
    slot: "a rule",
    document: {
      version: 2,
      fields: FIELDS,
      rules: [{ effect: "hidden", target: "b", when: { field: "a", operator: "isEmpty" }, nonsenseKey: 1 }],
    },
  },
  {
    slot: "a validation",
    document: {
      version: 2,
      fields: FIELDS,
      validations: [{ when: { op: "isEmpty", operands: [{ path: "a" }] }, message: "m", nonsenseKey: 1 }],
    },
  },
  {
    slot: "a layout node",
    document: {
      version: 2,
      fields: FIELDS,
      layout: [{ kind: "section", id: "s", children: ["a", "b"], nonsenseKey: 1 }],
    },
  },
]);

function saidAbout(document) {
  const parsed = parseDynamicForm(document, { mode: "lenient" });
  return { ok: parsed.ok, codes: parsed.diagnostics.map((each) => each.code) };
}

battle(
  {
    claims: ["DYN-004", "DYN-003"],
    title: "a key the published schema refuses is one the parser reports",
    environments: ["node"],
  },
  async (ctx) => {
    const observed = SLOTS.map((entry) => ({ slot: entry.slot, ...saidAbout(entry.document) }));
    ctx.log.note("what the parser says about a key nobody declared", observed);

    // The instrument: the same documents without the extra key must parse clean, or "nothing was
    // said" would be a statement about documents the parser was rejecting for another reason.
    const clean = SLOTS.map((entry) => {
      const stripped = JSON.parse(JSON.stringify(entry.document).replaceAll(',"nonsenseKey":1', ""));
      return { slot: entry.slot, ...saidAbout(stripped) };
    });
    expectClaim(clean.every((each) => each.codes.length === 0), {
      claimIds: ["DYN-004"],
      what: "a document is refused even without the unknown key, so the probe is wrong before the contract is",
      detail: JSON.stringify(clean),
    });

    expectEqual(
      observed.filter((each) => each.codes.length === 0).map((each) => each.slot),
      [],
      {
        claimIds: ["DYN-004", "DYN-003"],
        what: "a key the published JSON Schema refuses passed the parser without a word, and the parser is the only one of the three checks a stored or generated document ever meets",
      },
    );
  },
);
