/**
 * Public API surface report — prints every export of the packaged .d.ts
 * rollups so accidental exports are visible. Run after `npm run build:angular`;
 * pass a file path as the first argument to write the report there.
 */
import { readFileSync, writeFileSync } from "node:fs";

const entries = {
  "@modyra/angular": "packages/angular/dist/types/modyra-angular.d.ts",
  "@modyra/angular/adapter": "packages/angular/dist/types/modyra-angular-adapter.d.ts",
  "@modyra/angular/ui": "packages/angular/dist/types/modyra-angular-ui.d.ts",
  "@modyra/angular/zod": "packages/angular/dist/types/modyra-angular-zod.d.ts",
  "@modyra/angular/interop": "packages/angular/dist/types/modyra-angular-interop.d.ts",
};

let md = `# Public API surface

Generated by \`node scripts/api-surface.mjs\` from the packaged type rollups —
regenerate after every \`npm run build:angular\`. Review this file in code review:
anything appearing here is public API covered by semver.
`;

for (const [entry, file] of Object.entries(entries)) {
  const src = readFileSync(file, "utf8");
  const decls = [...src.matchAll(/^export declare (?:abstract )?(class|function|const|interface|type|enum) ([A-Za-z0-9_]+)/gm)]
    .map((m) => `${m[2]} (${m[1]})`);
  const reexports = [...src.matchAll(/^export \{([^}]+)\}/gms)]
    .flatMap((m) => m[1].split(",").map((s) => s.trim()).filter(Boolean));
  const all = [...new Set([...decls, ...reexports])].sort((a, b) => a.localeCompare(b));
  md += `\n## \`${entry}\` — ${all.length} exports\n\n`;
  for (const name of all) md += `- ${name}\n`;
}

const out = process.argv[2];
if (out) {
  writeFileSync(out, md);
  console.log(`${out} written`);
} else {
  console.log(md);
}
